### ISSUE TITLE
 whole screen just disappeared after clicking buttons

### ISSUE THREAD

**Issue by jingSUN2017** [aliafzal15/GameProject#21] opened 2017-03-21 02:21 UTC
I'm not sure that Chao you changed something for testing or due to some other unexpected reasons, after clicking most of the buttons( such as "Character Editor", "Start"), the whole screen just disappeared.

**Comment by chaowangCanada** [comment] 2017-03-21 02:27
Use the latest code, it works fine on my computer. 
Or you can paste the log, and error message here. I will diagnose.

**Comment by chaowangCanada** [comment] 2017-03-22 13:27
close this issue since QA cannot reproduce

**Closed as completed by chaowangCanada** 2017-03-22 13:27 UTC
